### ISSUE TITLE
Brainhack Reviewer Comments

### ISSUE THREAD

**Issue by leiliew** [Brainhack-Proceedings-2015/Das_HBM_LORIS#1]
Overall, this proceeding is well-organized and the completed work sounds very useful for the neuroimaging community! The biggest concern I have is that the github address (http://github.com/LORIS) does not seem to be accurate. Is this supposed to go to a gentleman named Loris Guignard’s site? Is there a different github address for this tool and/or the actual LORIS database?

The rest of my comments are meant as suggestions to strengthen the clarity and impact of this proceeding - they are not mandatory but should be quick to implement if desired.
1. The tagline “Advancing Open Science through NiData” is not so clear to me, as I wasn’t sure what NiData is or how it is relevant for this project?
2. The first statement could be reworded as a complete sentence: “The purpose of this Brainhack project was to..”
3. There are a few typos here and there (e.g., first sentence “directly on **a *_workstation”, third sentence “for *_the** anonymization).
4. In your second paragraph, I might acknowledge dicom anonymizers that do exist (e.g., "while a number of tools for anonymizing dicom images exist (e.g., dcm2nii, etc. etc. ), currently, a simple….")
5. In approach, you might say “Here, we created a DICOM anonymized that is a simple graphical tool…” (to make it clear that this is what you did for the project and not a pre-existing tool).
6. A small thing, but I would be consistent to use either DICOM or dicom (probably the all caps version is more correct) - e.g., in approach, second sentence, change “Dicom anonymizer” to “The DICOM anonymizer”
7. Results - first sentence, typo: “design to be easy-to-use, platform independent, and **have** minimum dependencies”. Second sentence, fragment, maybe revise to: “One zip file includes the original DICOM files and the other contains the anonymized DICOM outputs.”
8. A random question, but is there an option to use this tool from the command line as well? Or to batch process a large set of patient data? If so, I would highlight this in your approach and/or conclusions, as this would extend the utility of the tool and make it even more appealing. 
9. Figure - This is a great illustration of how to use the GUI. However, if possible, you might crop the image or remove the Figure description from the write up so you don’t have the Figure 1 legend twice at the bottom.

Please let me know if you have questions or comments!

Best wishes, and great work!
Lei

**Comment by cmadjar** [comment]
Dear Lei,

Thank you for reviewing our abstract.

You are right, we did not put the correct repository in the URL field. We have updated the link to the proper Github repository. Below are the answers regarding your other comments.
1. Sorry about this. I don't know what happened with the tagline. It should have been "LORIS: DICOM Anonymizer". This has been updated to the proper tagline.

2.-7. and 9. Thank you for the suggestions of improvements. They have been included in the latest version of the abstract.
1. Very good point. For now, we can only run it via a GUI but this would definitely be a future feature. Thank you for raising this.

Somehow, I cannot push the changes to the master branch, but I sent in a pull request with the changes here if you want to take a look: https://github.com/Brainhack-Proceedings-2015/Das_HBM_LORIS/pull/3/files
I'll investigate why I cannot push the changes to the master branch shortly

Thank you so much for the very helpful comments and suggestions.

Best wishes,

Cécile

**Comment by leiliew** [comment]
?Hi C?cile,

Great, thanks for making the changes - I think it's a very exciting project!

Only one thing - I still can't access the code? Is this supposed to be the new address: https://github.com/DICOM_anonymizer? ? Please let me know if I'm doing something wrong - thank you!

Best,

Lei

**Comment by cmadjar** [comment]
Hi Lei,

Very sorry, I made a typo in the URL. This should be fixed now. 

Thank you!
Best,

Cécile

**Comment by leiliew** [comment]
Hi Cécile,

I'm sorry, but it looks to me that you have two URLs listed, but neither works. This one is listed in most places:

https://github.com/DICOM/_anonymizer

and this one is listed once:

https://github.com/DICOM_anonymizer

I wasn't able to load either of these - can you confirm that one of these is correct and make sure it's consistent throughout your document? I was looking at this version you had referred to for the changes: https://github.com/Brainhack-Proceedings-2015/Das_HBM_LORIS/pull/3/files 

Thanks,
Lei

**Comment by cmadjar** [comment]
Hi Lei,

Sorry I was not clear. I made the changes directly on the master branch on Github (I have the permission to do it now). So if you look at the following link, you should see the updated URL on the PDF.
https://github.com/Brainhack-Proceedings-2015/Das_HBM_LORIS/blob/master/brainhack-report-formatted.pdf

Thank you and sorry again for the confusion. Let me know if you can't see it.
Best,

Cécile

**Comment by leiliew** [comment]
Got it - thanks! Looks great - thank you for making the edits and best of luck with everything!

Best,
Lei
